### ISSUE TITLE
Change cursor. 

### ISSUE THREAD

**Issue by raziraz** [krig-collective/krig.io#17]
Make the cursor a simple dot that changes color when hover over a contrast area.

**Comment by raziraz** [comment]
Example for reference http://zipl.pro/.

**Comment by jaweglin** [comment]
Changed so that the cursor is a pink circle, but perhaps we want to change the arrow to a black circle as in the example ref?

**Comment by jaweglin** [comment]
managed to get a black dot that gets bigger and pink when hover, but not for cookie concent and medlm and säker.online. Also the social icons the hover effect of scale transformation dissappeard.
