### ISSUE TITLE
Social buttons not visible on some devices.

### ISSUE THREAD

**Issue by Johannestegner** [krig-collective/krig.io#27]
On devices such as iPhone and Nexus6 the social buttons are not visible. They should be!

**Comment by raziraz** [comment]
This will be both a design task and implementation.

**Comment by jaweglin** [comment]
I made them visible on screen, but not sure about iphone and Nexus6 so have to check that

**Comment by Johannestegner** [comment]
Use the browser dev-tools to access UserAgent and size spoofing for most devices:
![image](https://user-images.githubusercontent.com/2530181/36718674-ee4cae8c-1ba2-11e8-897b-86b9fba42362.png)

:)

**Comment by Johannestegner** [comment]
Closes with 424b888
